### ISSUE TITLE
Non-Starter: "RuntimeError: maximum recursion depth exceeded while calling a Python object"

### ISSUE THREAD

**Issue by AndydeCleyre** [alixedi/palal#2]
I installed via pip and Python 3.4.3, and ran palal, yielding this output (abridged):

```
Traceback (most recent call last):
  File "/usr/bin/palal", line 9, in <module>
    load_entry_point('palal==0.1.2', 'console_scripts', 'palal')()
  File "/usr/lib/python3.4/site-packages/palal/__init__.py", line 3, in main
    palal.main()
  File "/usr/lib/python3.4/site-packages/palal/__init__.py", line 3, in main
    palal.main()
  File "/usr/lib/python3.4/site-packages/palal/__init__.py", line 3, in main
    palal.main()
  File "/usr/lib/python3.4/site-packages/palal/__init__.py", line 3, in main
    palal.main()
...
  File "/usr/lib/python3.4/site-packages/palal/__init__.py", line 3, in main
    palal.main()
  File "/usr/lib/python3.4/site-packages/palal/__init__.py", line 3, in main
    palal.main()
  File "/usr/lib/python3.4/site-packages/palal/__init__.py", line 3, in main
    palal.main()
  File "/usr/lib/python3.4/site-packages/palal/__init__.py", line 3, in main
    palal.main()
  File "/usr/lib/python3.4/site-packages/palal/__init__.py", line 2, in main
    import palal
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by alixedi** [comment]
Should be ok now. Thanks for your help!
